version: 2
updates:
- package-ecosystem: gomod
  directory: /
  registries: []
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  registries:
    - github-hpe
