name: GitHub Actions CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.21' ]
    name: Go ${{ matrix.go }} CI test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go version
      - run: make fmt 
      - run: make tools 
      - run: make lint
      - run: make test
      - run: make coverage
