# Copyright 2022-2024 Hewlett Packard Enterprise Development LP
name: Trivy
on:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner (go.mod)
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
